name: GitHub Actions Version Updater

# # Controls when the action will run.
# on:
#   schedule:
#   # Automatically run on every Sunday
#   - cron:  '0 0 * * 0'
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
  runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3
    with:
      token: ${{ secrets.MME_WORKFLOWSECRET }} # [Required] Access token with `workflow` scope.
  - name: Run GitHub Actions Version Updater
    uses: saadmk11/github-actions-version-updater@v0.8.1
    with:
      token: ${{ secrets.MME_WORKFLOWSECRET }} # [Required] Access token with `workflow` scope.
